/**
 * Workflow types for the autopilot runner.
 * A Workflow is a DAG of steps generated by the LLM from a natural language task.
 */

export type Workflow = {
  version: 1;
  id: string;
  name?: string;
  description?: string;
  concurrency?: number;
  steps: WorkflowStep[];
  defaults?: Record<string, unknown>;
};

export type WorkflowStep = {
  id: string;
  type: "agent.run";
  goal: string;
  dependsOn?: string[];
  context?: string;
  adapterRequest?: Record<string, unknown>;
  [key: string]: unknown;
};

export type StepResult = {
  stepId: string;
  status: "succeeded" | "failed" | "skipped";
  sessionId: string;
  outputText: string;
  usage?: { inputTokens: number; outputTokens: number };
  error?: string;
};

export type CompletionCheck =
  | { done: true; summary: string }
  | { done: false; reason: string; nextWorkflow?: Workflow };
